using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace WebssASP
{
    public partial class HelloWorld : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            //this method executes BEFORE any event method on EACH processing of this webpage
            OutputArea.ForeColor = System.Drawing.Color.Black;
            OutputArea.Text = "";
            OutputArea.Font.Size = 20;
        }

        protected void Button1_Click(object sender, EventArgs e)
        {
            //this method stub for the button was generated by 
            // double click the button control on your web form 
            // while in design veiw.

            //when the pressme button is pressed this code will 
            //be executed
            //this is called event driven logic
            // the event was the pressing of the button
            //see the onClick property of you control 
            // on the web page
            // the ID name of the control acts as the variable name 
            //      in your code
            //Since, each control is a class instance, access to 
            // the contents of a class is by the class properties
            //JUST like RAZOR, 95% of all data is returned as a string

            if (string.IsNullOrEmpty(NameArg.Text))
            {
                OutputArea.Text = "Enter your name, please";
            }
            else
            {
                OutputArea.Text = "Hello " + NameArg.Text;
                OutputArea.ForeColor = System.Drawing.Color.Red;
                OutputArea.Font.Size = 100;
            }
        }
    }
}